version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
    - checkout: 
    - run: npm install
    - save_cache: 
        key: npm-cache-{{ .Branch }}-{{ checksum "package.json"}}
        paths: 
        - node_modules
      