version: 2.1.3
build:
  one:
    docker:
      - image: docker:latest
        environment: 
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:13.2-postgis-ram
    steps: 
      - checkout
      - run: sudo apk update
      - run: sudo apk install postgresql-13.2
      - run: whoami
      - run: |
          psql \ 
          -d $TEST_DATABASE_URL \ 
          - c "CREATE TABLE test (name (char(25));"
      - run: | 
          psql \
          -d $TEST_DATABASE_URL \ 
          - c "INSERT INTO test VALUES ('Joe', ('Joey') ('Julian');"
      - run: | 
          psql \ 
          -d $TEST_DATABASE_URL \ 
          -c "SELECT * FROM test"