version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
    - checkout
    - run: apk update && apk install curl
    - run: curl -sL https://deb.nodesource.com/setup_13.x | bash -
    - run: apk update && apk install nodejs
    - run: npm install
    - save_cache: 
        key: npm-cache-{{ .Branch }}-{{ checksum "package.json"}}
        paths: 
        - node_modules
      