version: 2
jobs: 
  one: 
    docker: 
      - image: docker:latest 
    steps:
      - checkout 
      - run: echo "Hello World!" 
  two: 
    docker: # it runs inside a docker image, the same as above.
      - image: docker:latest
    steps:
      - checkout
      - run: echo "Hello World Again" 
# Define our workflows 
workflows:
  version: 2
  one_and_two: 
    jobs: 
      - one
      - two