version: 2.1.3
jobs:
  build:
    docker:
      - image: docker:latest
        environment: 
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:13.2-postgis-ram
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps: 
      - checkout
      - run: apk update
      - run: apk add postgresql-client-13.2
      - run: whoami
      - run: |
          psql \ 
          -d $TEST_DATABASE_URL \ 
          - c "CREATE TABLE test (name (char(25));"
      - run: | 
          psql \
          -d $TEST_DATABASE_URL \ 
          - c "INSERT INTO test VALUES ('Joe', ('Joey') ('Julian');"
      - run: | 
          psql \ 
          -d $TEST_DATABASE_URL \ 
          -c "SELECT * FROM test"