version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
    - checkout
    - run: apk update && apk add curl
    - run: curl -sL https://deb.nodesource.com/setup_13.x 
    - run: apk update && apk add nodejs
    - run: apk add npm
    - save_cache: 
        key: npm-cache-{{ .Branch }}-{{ checksum "package.json"}}
        paths: 
        - node_modules
      