version: 2
jobs: 
  one: 
    docker: 
      - image: docker:latest 
    steps:
      - checkout 
      - run: echo "Hello World!" 
      - run: mkdir -p my_workspace
      - run: echo "Testing my workspace" > my_workspace/test
      - persist_to_workspace: 
          root: my_workspace
          paths: 
            - test
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "A more familiar hi"  
      - attach_workspace:
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          # check first step before processing second
          requires:
            - one